<>
    <p>Below is a summary/overview of the major data types generated by the CCs. The aim of the diagram and table below is to highlight the connections between the GCCs, sequencing platforms, assays, and molecular features that will be present on the SMaHT Data Portal.</p>
    <p>Discover more about SMaHT data by hovering, clicking and dragging different parts of the diagram and table below.</p>
    <Alluvial />
</>