<>
    <p>Below is the summary/overview of the major data types generated by the GCCs. To see the connection between each column, please hover over for interactive visualization.</p>
    <Alluvial />
</>