FROM opensearchproject/opensearch:2.6.0


MAINTAINER William Ronchetti "william_ronchetti@hms.harvard.edu"

ENV OPENSEARCH_VERSION="2.6.0"
ENV OPENSEARCH_SERVICE_PORT=9200
EXPOSE $OPENSEARCH_SERVICE_PORT
