from snovault.project.loadxl import SnovaultProjectLoadxl


class SMaHTProjectLoadxl(SnovaultProjectLoadxl):
    # N.B. snovault.loadxl expects to get this in snake-case (not camel-case) format.
    order = [
        "access_key",
        "user",
        "consortium",
        "submission_center",
        "file_format",
        "quality_metric",
        "reference_genome",
        "software",
        "tracking_item",
        "image",
        "document",
        "static_section",
        "page",
        "filter_set",
        "generic_qc_config",
        "higlass_view_config",
        "ingestion_submission",
        "ontology",
        "ontology_term",
        "protocol",
        "protected_donor",
        "donor",
        "demographic",
        "medical_history",
        "diagnosis",
        "exposure",
        "family_history",
        "medical_treatment",
        "death_circumstances",
        "tissue_collection",
        "tissue",
        "tissue_sample",
        "brain_pathology_report",
        "non_brain_pathology_report",
        "histology_image",
        "cell_line",
        "cell_culture",
        "cell_culture_mixture",
        "preparation_kit",
        "treatment",
        "cell_culture_sample",
        "cell_sample",
        "analyte",
        "analyte_preparation",
        "assay",
        "library",
        "library_preparation",
        "sequencer",
        "sequencing",
        "file_set",
        "analysis_run",
        "external_quality_metric",
        "reference_file",
        "resource_file",
        "unaligned_reads",
        "aligned_reads",
        "variant_calls",
        "output_file",
        "workflow",
        "workflow_run",
        "meta_workflow",
        "meta_workflow_run",
        "donor_specific_assembly",
        "supplementary_file",
    ]

    def loadxl_order(self):
        """Defines any hard orderings that must happen when reindexing types"""
        return self.order


ITEM_INDEX_ORDER = SMaHTProjectLoadxl.order
