# generated by datamodel-codegen:
#   filename:  analyte.json
#   timestamp: 2024-03-15T18:19:16+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional, Union
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    constr,
)


class Tag(RootModel[constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=50)]):
    root: constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=50) = Field(
        ..., description='A tag for the item.', title='Tag'
    )


class Status(Enum):
    public = 'public'
    draft = 'draft'
    released = 'released'
    in_review = 'in review'
    obsolete = 'obsolete'
    deleted = 'deleted'
    restricted = 'restricted'


class LastModified(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date_modified: Optional[Union[AwareDatetime, date]] = Field(
        None,
        description='Do not submit, value is assigned by the server. The date the object is modified.',
        title='Date Modified',
    )
    modified_by: Optional[str] = Field(
        None,
        description='Do not submit, value is assigned by the server. The user that modfied the object.',
        title='Modified By',
    )


class ConcentrationUnit(Enum):
    ng_uL = 'ng/uL'
    mg_mL = 'mg/mL'


class MoleculeEnum(Enum):
    DNA = 'DNA'
    RNA = 'RNA'


class MoleculeDetailEnum(Enum):
    Total_DNA = 'Total DNA'
    mRNA = 'mRNA'
    tRNA = 'tRNA'
    rRNA = 'rRNA'
    MicroRNA = 'MicroRNA'
    Total_RNA = 'Total RNA'


class RnaIntegrityNumberInstrument(Enum):
    Agilent_Bioanalyzer = 'Agilent Bioanalyzer'
    Caliper_Life_Sciences_LabChip_GX = 'Caliper Life Sciences LabChip GX'


class SampleQuantityUnit(Enum):
    cells = 'cells'
    uL = 'uL'
    mL = 'mL'
    ug = 'ug'
    mg = 'mg'
    g = 'g'


class VolumeUnit(Enum):
    uL = 'uL'
    mL = 'mL'


class PrincipalsAllowed(BaseModel):
    view: Optional[str] = None
    edit: Optional[str] = None


class Analyte(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: Optional[UUID] = Field(None, title='UUID')
    tags: Optional[List[Tag]] = Field(
        None,
        description='Key words that can tag an item - useful for filtering.',
        title='Tags',
    )
    submitted_id: constr(pattern=r'^[A-Z0-9]{3,}_ANALYTE_[A-Z0-9-_.]{4,}$') = Field(
        ..., description='Identifier on submission', title='Submitter ID'
    )
    date_created: Optional[Union[AwareDatetime, date]] = Field(
        None, title='Date Created'
    )
    submitted_by: Optional[str] = Field(None, title='Submitted By')
    status: Optional[Status] = Field('in review', title='Status')
    schema_version: Optional[constr(pattern=r'^\\d+(\\.\\d+)*$')] = Field(
        '2', title='Schema Version'
    )
    protocols: Optional[List[str]] = Field(
        None,
        description='Protocols providing experimental details',
        min_length=1,
        title='Protocols',
    )
    last_modified: Optional[LastModified] = Field(None, title='Last Modified')
    description: Optional[str] = Field(
        None, description='Plain text description of the item', title='Description'
    )
    submission_centers: List[str] = Field(
        ...,
        description='Submission Centers that created this item.',
        title='Generated By',
    )
    consortia: Optional[List[str]] = Field(
        None, description='Consortia associated with this item.', title='Consortia'
    )
    accession: Optional[str] = Field(
        None,
        description='A unique identifier to be used to reference the object.',
        title='Accession',
    )
    alternate_accessions: Optional[List[str]] = Field(
        None,
        description='Accessions previously assigned to objects that have been merged with this object.',
        title='Alternate Accessions',
    )
    a260_a280_ratio: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Ratio of nucleic acid absorbance at 260 nm and 280 nm, used to determine a measure of DNA purity',
        title='A260/A280 Ratio',
    )
    concentration: Optional[confloat(ge=0.0)] = Field(
        None, description='Analyte concentration', title='Concentration'
    )
    concentration_unit: Optional[ConcentrationUnit] = Field(
        None, description='Unit of the concentration', title='Concentration Unit'
    )
    molecule: List[MoleculeEnum] = Field(
        ...,
        description='Molecule of interest for the analyte',
        min_length=1,
        title='Molecule',
    )
    molecule_detail: List[MoleculeDetailEnum] = Field(
        ...,
        description='Biological features included in the analyte',
        min_length=1,
        title='Molecule Detail',
    )
    ribosomal_rna_ratio: Optional[confloat(ge=0.0)] = Field(
        None,
        description='The 28S/18S ribosomal RNA band ratio used to assess the quality of total RNA',
        title='Ribosomal RNA Ratio',
    )
    rna_integrity_number: Optional[confloat(ge=1.0, le=10.0)] = Field(
        None,
        description='Assessment of the integrity of RNA based on electrophoresis',
        title='RNA Integrity Number',
    )
    rna_integrity_number_instrument: Optional[RnaIntegrityNumberInstrument] = Field(
        None, description='Instrument used for RIN assessment', title='RIN Instrument'
    )
    sample_quantity: Optional[confloat(ge=0.0)] = Field(
        None,
        description='The amount of sample used to generate the analyte',
        title='Sample Quantity',
    )
    sample_quantity_unit: Optional[SampleQuantityUnit] = Field(
        None, description='Unit of the sample quantity', title='Sample Quantity Unit'
    )
    volume: Optional[confloat(ge=0.0)] = Field(
        None, description='Analyte volume', title='Volume'
    )
    volume_unit: Optional[VolumeUnit] = Field(
        None, description='Unit of the volume', title='Volume Unit'
    )
    analyte_preparation: Optional[str] = Field(
        None,
        description='Link to associated analyte preparation',
        title='Analyte Preparation',
    )
    samples: List[str] = Field(
        ..., description='Link to associated samples', min_length=1, title='Samples'
    )
    field_id: Optional[str] = Field(None, alias='@id', title='ID')
    field_type: Optional[List[str]] = Field(None, alias='@type', title='Type')
    principals_allowed: Optional[PrincipalsAllowed] = Field(
        None,
        description='Calculated permissions used for ES filtering',
        title='principals_allowed',
    )
    display_title: Optional[str] = Field(None, title='Display Title')
