# generated by datamodel-codegen:
#   filename:  analyte_preparation.json
#   timestamp: 2024-03-15T18:19:16+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional, Union
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr


class Tag(RootModel[constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=50)]):
    root: constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=50) = Field(
        ..., description='A tag for the item.', title='Tag'
    )


class Status(Enum):
    public = 'public'
    draft = 'draft'
    released = 'released'
    in_review = 'in review'
    obsolete = 'obsolete'
    deleted = 'deleted'
    restricted = 'restricted'


class LastModified(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date_modified: Optional[Union[AwareDatetime, date]] = Field(
        None,
        description='Do not submit, value is assigned by the server. The date the object is modified.',
        title='Date Modified',
    )
    modified_by: Optional[str] = Field(
        None,
        description='Do not submit, value is assigned by the server. The user that modfied the object.',
        title='Modified By',
    )


class CellLysisMethodEnum(Enum):
    Chemical = 'Chemical'
    Enzymatic = 'Enzymatic'
    Mechanical = 'Mechanical'
    Thermal = 'Thermal'


class ExtractionMethodEnum(Enum):
    Magnetic_Beads = 'Magnetic Beads'
    Not_Applicable = 'Not Applicable'
    Organic_Chemicals = 'Organic Chemicals'
    Silica_Column = 'Silica Column'


class PrincipalsAllowed(BaseModel):
    view: Optional[str] = None
    edit: Optional[str] = None


class AnalytePreparation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: Optional[UUID] = Field(None, title='UUID')
    tags: Optional[List[Tag]] = Field(
        None,
        description='Key words that can tag an item - useful for filtering.',
        title='Tags',
    )
    submitted_id: constr(
        pattern=r'^[A-Z0-9]{3,}_ANALYTE-PREPARATION_[A-Z0-9-_.]{4,}$'
    ) = Field(..., description='Identifier on submission', title='Submitter ID')
    date_created: Optional[Union[AwareDatetime, date]] = Field(
        None, title='Date Created'
    )
    submitted_by: Optional[str] = Field(None, title='Submitted By')
    status: Optional[Status] = Field('in review', title='Status')
    schema_version: Optional[constr(pattern=r'^\\d+(\\.\\d+)*$')] = Field(
        '1', title='Schema Version'
    )
    last_modified: Optional[LastModified] = Field(None, title='Last Modified')
    submission_centers: List[str] = Field(
        ...,
        description='Submission Centers that created this item.',
        title='Generated By',
    )
    consortia: Optional[List[str]] = Field(
        None, description='Consortia associated with this item.', title='Consortia'
    )
    accession: Optional[str] = Field(
        None,
        description='A unique identifier to be used to reference the object.',
        title='Accession',
    )
    alternate_accessions: Optional[List[str]] = Field(
        None,
        description='Accessions previously assigned to objects that have been merged with this object.',
        title='Alternate Accessions',
    )
    cell_lysis_method: Optional[List[CellLysisMethodEnum]] = Field(
        None,
        description='Cell lysis method for analyte extraction',
        min_length=1,
        title='Cell Lysis Method',
    )
    extraction_method: Optional[List[ExtractionMethodEnum]] = Field(
        None, min_length=1, title='Extraction Method'
    )
    preparation_kits: Optional[List[str]] = Field(
        None,
        description='Links to associated preparation kit',
        min_length=1,
        title='Preparation Kits',
    )
    treatments: Optional[List[str]] = Field(
        None,
        description='Links to associated treatments',
        min_length=1,
        title='Treatments',
    )
    field_id: Optional[str] = Field(None, alias='@id', title='ID')
    field_type: Optional[List[str]] = Field(None, alias='@type', title='Type')
    principals_allowed: Optional[PrincipalsAllowed] = Field(
        None,
        description='Calculated permissions used for ES filtering',
        title='principals_allowed',
    )
    display_title: Optional[str] = Field(None, title='Display Title')
