# generated by datamodel-codegen:
#   filename:  cell_culture.json
#   timestamp: 2024-03-15T18:19:16+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional, Union
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class Tag(RootModel[constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=50)]):
    root: constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=50) = Field(
        ..., description='A tag for the item.', title='Tag'
    )


class Status(Enum):
    public = 'public'
    draft = 'draft'
    released = 'released'
    in_review = 'in review'
    obsolete = 'obsolete'
    deleted = 'deleted'
    restricted = 'restricted'


class LastModified(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date_modified: Optional[Union[AwareDatetime, date]] = Field(
        None,
        description='Do not submit, value is assigned by the server. The date the object is modified.',
        title='Date Modified',
    )
    modified_by: Optional[str] = Field(
        None,
        description='Do not submit, value is assigned by the server. The user that modfied the object.',
        title='Modified By',
    )


class PrincipalsAllowed(BaseModel):
    view: Optional[str] = None
    edit: Optional[str] = None


class CellCulture(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accession: Optional[str] = Field(
        None,
        description='A unique identifier to be used to reference the object.',
        title='Accession',
    )
    schema_version: Optional[constr(pattern=r'^\\d+(\\.\\d+)*$')] = Field(
        '2', title='Schema Version'
    )
    sample_count: Optional[conint(ge=1)] = Field(
        None,
        description='Number of samples produced for this source',
        title='Sample Count',
    )
    submitted_id: constr(pattern=r'^[A-Z0-9]{3,}_CELL-CULTURE_[A-Z0-9-_.]{4,}$') = (
        Field(..., description='Identifier on submission', title='Submitter ID')
    )
    uuid: Optional[UUID] = Field(None, title='UUID')
    tags: Optional[List[Tag]] = Field(
        None,
        description='Key words that can tag an item - useful for filtering.',
        title='Tags',
    )
    date_created: Optional[Union[AwareDatetime, date]] = Field(
        None, title='Date Created'
    )
    submitted_by: Optional[str] = Field(None, title='Submitted By')
    status: Optional[Status] = Field('in review', title='Status')
    protocols: Optional[List[str]] = Field(
        None,
        description='Protocols providing experimental details',
        min_length=1,
        title='Protocols',
    )
    last_modified: Optional[LastModified] = Field(None, title='Last Modified')
    description: Optional[str] = Field(
        None, description='Plain text description of the item', title='Description'
    )
    submission_centers: List[str] = Field(
        ...,
        description='Submission Centers that created this item.',
        title='Generated By',
    )
    consortia: Optional[List[str]] = Field(
        None, description='Consortia associated with this item.', title='Consortia'
    )
    alternate_accessions: Optional[List[str]] = Field(
        None,
        description='Accessions previously assigned to objects that have been merged with this object.',
        title='Alternate Accessions',
    )
    culture_duration: Optional[conint(ge=0)] = Field(
        None, description='Total number of culturing days', title='Culture Duration'
    )
    culture_harvest_date: Optional[date] = Field(
        None,
        description='YYYY-MM-DD format date for cell culture harvest',
        title='Culture Harvest Date',
    )
    culture_start_date: Optional[date] = Field(
        None,
        description='YYYY-MM-DD format date for cell culture start date',
        title='Culture Start Date',
    )
    growth_medium: Optional[str] = Field(
        None, description='Medium used for cell culture', title='Growth Medium'
    )
    karyotype: Optional[str] = Field(
        None,
        description='Chromosome count and any noted rearrangements or copy number variation',
        title='Karyotype',
    )
    lot_number: Optional[List[str]] = Field(
        None, description='Lot number of cell line', title='Lot Number'
    )
    passage_number: Optional[conint(ge=0)] = Field(
        None,
        description='Number of times the cell line has been passaged since the culture start date until harvest',
        title='Passage Number',
    )
    cell_line: str = Field(
        ..., description='Cell line used for the cell culture', title='Cell Line'
    )
    field_id: Optional[str] = Field(None, alias='@id', title='ID')
    field_type: Optional[List[str]] = Field(None, alias='@type', title='Type')
    principals_allowed: Optional[PrincipalsAllowed] = Field(
        None,
        description='Calculated permissions used for ES filtering',
        title='principals_allowed',
    )
    display_title: Optional[str] = Field(None, title='Display Title')
