# generated by datamodel-codegen:
#   filename:  library.json
#   timestamp: 2024-03-15T18:19:17+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional, Union
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class Tag(RootModel[constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=50)]):
    root: constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=50) = Field(
        ..., description='A tag for the item.', title='Tag'
    )


class Status(Enum):
    public = 'public'
    draft = 'draft'
    released = 'released'
    in_review = 'in review'
    obsolete = 'obsolete'
    deleted = 'deleted'
    restricted = 'restricted'


class LastModified(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date_modified: Optional[Union[AwareDatetime, date]] = Field(
        None,
        description='Do not submit, value is assigned by the server. The date the object is modified.',
        title='Date Modified',
    )
    modified_by: Optional[str] = Field(
        None,
        description='Do not submit, value is assigned by the server. The user that modfied the object.',
        title='Modified By',
    )


class PrincipalsAllowed(BaseModel):
    view: Optional[str] = None
    edit: Optional[str] = None


class Library(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uuid: Optional[UUID] = Field(None, title='UUID')
    tags: Optional[List[Tag]] = Field(
        None,
        description='Key words that can tag an item - useful for filtering.',
        title='Tags',
    )
    submitted_id: constr(pattern=r'^[A-Z0-9]{3,}_LIBRARY_[A-Z0-9-_.]{4,}$') = Field(
        ..., description='Identifier on submission', title='Submitter ID'
    )
    date_created: Optional[Union[AwareDatetime, date]] = Field(
        None, title='Date Created'
    )
    submitted_by: Optional[str] = Field(None, title='Submitted By')
    status: Optional[Status] = Field('in review', title='Status')
    schema_version: Optional[constr(pattern=r'^\\d+(\\.\\d+)*$')] = Field(
        '1', title='Schema Version'
    )
    protocols: Optional[List[str]] = Field(
        None,
        description='Protocols providing experimental details',
        min_length=1,
        title='Protocols',
    )
    last_modified: Optional[LastModified] = Field(None, title='Last Modified')
    description: Optional[str] = Field(
        None, description='Plain text description of the item', title='Description'
    )
    submission_centers: List[str] = Field(
        ...,
        description='Submission Centers that created this item.',
        title='Generated By',
    )
    consortia: Optional[List[str]] = Field(
        None, description='Consortia associated with this item.', title='Consortia'
    )
    accession: Optional[str] = Field(
        None,
        description='A unique identifier to be used to reference the object.',
        title='Accession',
    )
    alternate_accessions: Optional[List[str]] = Field(
        None,
        description='Accessions previously assigned to objects that have been merged with this object.',
        title='Alternate Accessions',
    )
    a260_a280_ratio: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Ratio of nucleic acid absorbance at 260 nm and 280 nm, used to determine a measure of DNA purity',
        title='A260 A280 Ratio',
    )
    adapter_name: Optional[str] = Field(
        None, description='Name of sequencing adapter', title='Adapter Name'
    )
    adapter_sequence: Optional[str] = Field(
        None,
        description='Base sequence of sequencing adapter',
        title='Adapter Sequence',
    )
    amplification_cycles: Optional[conint(ge=0)] = Field(
        None,
        description='Number of PCR Cycles used for additional amplification',
        title='Amplification Cycles',
    )
    analyte_weight: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Weight of analyte used to prepare library (mg)',
        title='Analyte Weight',
    )
    barcode_sequences: Optional[List[str]] = Field(
        None,
        description='Barcode sequence for multiplexed sequencing',
        min_length=1,
        title='Barcode Sequences',
    )
    fragment_maximum_length: Optional[conint(ge=0)] = Field(
        None,
        description='Maximum length of the sequenced fragments (e.g., as predicted by Agilent Bioanalyzer)',
        title='Fragment Maximum Length',
    )
    fragment_mean_length: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Mean length of the sequenced fragments (e.g., as predicted by Agilent Bioanalyzer)',
        title='Fragment Mean Length',
    )
    fragment_minimum_length: Optional[conint(ge=0)] = Field(
        None,
        description='Minimum length of the sequenced fragments (e.g., as predicted by Agilent Bioanalyzer)',
        title='Fragment Minimum Length',
    )
    fragment_standard_deviation_length: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Standard deviation of length of the sequenced fragments (e.g., as predicted by Agilent Bioanalyzer)',
        title='Fragment Standard Deviation Length',
    )
    insert_coefficient_of_variation: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Coefficient of variation of the length of the sample molecule in the fragments to be sequenced',
        title='Insert Coefficient of Variation',
    )
    insert_maximum_length: Optional[conint(ge=0)] = Field(
        None,
        description='Maximum length of the sample molecule in the fragments to be sequenced',
        title='Insert Maximum Length',
    )
    insert_mean_length: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Mean length of the sample molecule in the fragments to be sequenced',
        title='Insert Mean Length',
    )
    insert_minimum_length: Optional[conint(ge=0)] = Field(
        None,
        description='Minimum length of the sample molecule in the fragments to be sequenced',
        title='Insert Minimum Length',
    )
    insert_standard_deviation_length: Optional[confloat(ge=0.0)] = Field(
        None,
        description='Standard deviation of the length of the sample molecule in the fragments to be sequenced',
        title='Insert Standard Deviation Length',
    )
    preparation_date: Optional[date] = Field(
        None, description='Date of library preparation', title='Preparation Date'
    )
    target_insert_maximum_length: Optional[conint(ge=0)] = Field(
        None,
        description='Target maximum length of the insert (bp)',
        title='Target Insert Maximum Length',
    )
    target_insert_mean_length: Optional[conint(ge=0)] = Field(
        None,
        description='Target mean length of the insert (bp)',
        title='Target Insert Mean Length',
    )
    target_insert_minimum_length: Optional[conint(ge=0)] = Field(
        None,
        description='Target minimum length of the insert (bp)',
        title='Target Insert Minimum Length',
    )
    analyte: str = Field(..., description='Link to associated analyte', title='Analyte')
    assay: Optional[str] = Field(
        None, description='Link to associated assay', title='Assay'
    )
    library_preparation: Optional[str] = Field(
        None,
        description='Link to associated library preparation',
        title='Library Preparation',
    )
    field_id: Optional[str] = Field(None, alias='@id', title='ID')
    field_type: Optional[List[str]] = Field(None, alias='@type', title='Type')
    principals_allowed: Optional[PrincipalsAllowed] = Field(
        None,
        description='Calculated permissions used for ES filtering',
        title='principals_allowed',
    )
    display_title: Optional[str] = Field(None, title='Display Title')
