# generated by datamodel-codegen:
#   filename:  submitted_item.json
#   timestamp: 2024-03-15T18:19:19+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class PrincipalsAllowed(BaseModel):
    view: Optional[str] = None
    edit: Optional[str] = None


class Model(BaseModel):
    field_id: Optional[str] = Field(None, alias='@id', title='ID')
    field_type: Optional[List[str]] = Field(None, alias='@type', title='Type')
    principals_allowed: Optional[PrincipalsAllowed] = Field(
        None,
        description='Calculated permissions used for ES filtering',
        title='principals_allowed',
    )
    display_title: Optional[str] = Field(None, title='Display Title')
