# generated by datamodel-codegen:
#   filename:  tissue.json
#   timestamp: 2024-03-15T18:19:18+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Optional, Union
from uuid import UUID

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)


class Tag(RootModel[constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=50)]):
    root: constr(pattern=r'^[a-zA-Z0-9_-]+$', min_length=1, max_length=50) = Field(
        ..., description='A tag for the item.', title='Tag'
    )


class Status(Enum):
    public = 'public'
    draft = 'draft'
    released = 'released'
    in_review = 'in review'
    obsolete = 'obsolete'
    deleted = 'deleted'
    restricted = 'restricted'


class LastModified(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    date_modified: Optional[Union[AwareDatetime, date]] = Field(
        None,
        description='Do not submit, value is assigned by the server. The date the object is modified.',
        title='Date Modified',
    )
    modified_by: Optional[str] = Field(
        None,
        description='Do not submit, value is assigned by the server. The user that modfied the object.',
        title='Modified By',
    )


class PrincipalsAllowed(BaseModel):
    view: Optional[str] = None
    edit: Optional[str] = None


class Tissue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    accession: Optional[str] = Field(
        None,
        description='A unique identifier to be used to reference the object.',
        title='Accession',
    )
    schema_version: Optional[constr(pattern=r'^\\d+(\\.\\d+)*$')] = Field(
        '1', title='Schema Version'
    )
    sample_count: Optional[conint(ge=1)] = Field(
        None,
        description='Number of samples produced for this source',
        title='Sample Count',
    )
    submitted_id: constr(pattern=r'^[A-Z0-9]{3,}_TISSUE_[A-Z0-9-_.]{4,}$') = Field(
        ..., description='Identifier on submission', title='Submitter ID'
    )
    uuid: Optional[UUID] = Field(None, title='UUID')
    tags: Optional[List[Tag]] = Field(
        None,
        description='Key words that can tag an item - useful for filtering.',
        title='Tags',
    )
    date_created: Optional[Union[AwareDatetime, date]] = Field(
        None, title='Date Created'
    )
    submitted_by: Optional[str] = Field(None, title='Submitted By')
    status: Optional[Status] = Field('in review', title='Status')
    last_modified: Optional[LastModified] = Field(None, title='Last Modified')
    submission_centers: List[str] = Field(
        ...,
        description='Submission Centers that created this item.',
        title='Generated By',
    )
    consortia: Optional[List[str]] = Field(
        None, description='Consortia associated with this item.', title='Consortia'
    )
    alternate_accessions: Optional[List[str]] = Field(
        None,
        description='Accessions previously assigned to objects that have been merged with this object.',
        title='Alternate Accessions',
    )
    ischemic_time: Optional[conint(ge=0)] = Field(
        None, description='Time interval of ischemia in minutes', title='Ischemic Time'
    )
    pathology_notes: Optional[str] = Field(
        None,
        description='Notes from pathologist report on the tissue',
        title='Pathology Notes',
    )
    ph: Optional[confloat(ge=0.0, le=14.0)] = Field(
        None, description='pH of the tissue', title='pH'
    )
    preservation_time_interval: Optional[conint(ge=0)] = Field(
        None,
        description='Time interval from beginning of tissue recovery until placed in preservation media in minutes',
        title='Preservation Time Interval',
    )
    prosector_notes: Optional[str] = Field(
        None,
        description='Notes from prosector report on the tissue recovery',
        title='Prosector Notes',
    )
    recovery_datetime: Optional[Union[AwareDatetime, date]] = Field(
        None, description='Date and time of tissue recovery', title='Recovery Datetime'
    )
    recovery_interval: Optional[conint(ge=0)] = Field(
        None,
        description='Total time interval of tissue recovery in minutes',
        title='Recovery Interval',
    )
    size: Optional[confloat(ge=0.0)] = Field(
        None, description='Size of the tissue in cubic centimeters', title='Size'
    )
    uberon_id: constr(pattern=r'^UBERON:[0-9]{7}$') = Field(
        ..., description='Uberon identifier for the tissue', title='Uberon Id'
    )
    volume: Optional[confloat(ge=0.0)] = Field(
        None, description='Volume of the tissue in milliliters', title='Volume'
    )
    weight: Optional[confloat(ge=0.0)] = Field(
        None, description='Weight of the tissue in grams', title='Weight'
    )
    donor: str = Field(..., description='Link to the associated donor', title='Donor')
    field_id: Optional[str] = Field(None, alias='@id', title='ID')
    field_type: Optional[List[str]] = Field(None, alias='@type', title='Type')
    principals_allowed: Optional[PrincipalsAllowed] = Field(
        None,
        description='Calculated permissions used for ES filtering',
        title='principals_allowed',
    )
    display_title: Optional[str] = Field(None, title='Display Title')
