# Build for smaht-portal

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Test Suite for smaht-portal

    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Build matrix
    strategy:
      matrix:
        test_type: [ 'UNIT', 'DOCKER' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install/Link Postgres
        if: ${{ matrix.test_type == 'UNIT' }}
        run: |
          sudo apt-get install curl ca-certificates gnupg
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          sudo apt-get update
          sudo apt-get install postgresql-11 postgresql-client-11
          echo "/usr/lib/postgresql/11/bin" >> $GITHUB_PATH
          sudo ln -s /usr/lib/postgresql/11/bin/initdb /usr/local/bin/initdb

      - name: Install Deps
        if: ${{ matrix.test_type == 'UNIT' }}
        run: |
          make build

      - name: Generate egg-info
        run: python setup.py egg_info

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: QA (UNIT)
        if: ${{ matrix.test_type == 'UNIT' }}
        env:
          # S3_ENCRYPT_KEY: ${{ secrets.S3_ENCRYPT_KEY }}
          # # The need for this old environment variable name will go away soon.
          # TRAVIS_JOB_ID: sno-x-test-${{ github.run_number }}-
          # This will be the new environment variable name.
          TEST_JOB_ID: smaht-test-indexing-${{ github.run_number }}-${{ matrix.python_version }}-
        run: |
          make remote-test

      - name: Docker Build
        if: ${{ matrix.test_type == 'DOCKER' }}
        run: |
          touch deploy/docker/local/docker_development.ini  # cheap substitute for prepare-docker to make ignored file
          docker build .

      - name: Cleanup
        if: ${{ always() && matrix.test_type == 'UNIT' }}
        env:
          S3_ENCRYPT_KEY: ${{ secrets.S3_ENCRYPT_KEY }}
          # The need for this old environment variable name will go away soon.
          # TRAVIS_JOB_ID: sno-x-test-${{ github.run_number }}-
          # This will be the new environment variable name.
          TEST_JOB_ID: smaht-test-indexing-${{ github.run_number }}-${{ matrix.python_version }}-
        run: |
          poetry run wipe-test-indices $TEST_JOB_ID search-opensearch-smaht-testing-ykavtw57jz4cx4f2gqewhu4b44.us-east-1.es.amazonaws.com:443
